local colors = require('gruvbox.palette')

require('gruvbox').setup {
  undercurl            = true,
  underline            = true,
  bold                 = true,
  italic               = true,
  strikethrough        = true,
  invert_selection     = false,
  invert_signs         = false,
  invert_tabline       = false,
  invert_intend_guides = false,
  inverse              = true,
  contrast             = 'soft',
  palette_overrides    = {},
  overrides            = {
    FloatBorder                  = { fg     = colors.dark3, bg = 'None' },
    NormalFloat                  = { link   = 'Normal' },
    FloatTitle                   = { link   = 'Normal' },
    Operator                     = { italic = false },
    -- Telescope
    TelescopePromptBorder        = { link   = 'FloatBorder' },
    TelescopeResultsBorder       = { link   = 'FloatBorder' },
    TelescopePreviewBorder       = { link   = 'FloatBorder' },
    -- Bufferline
    BufferlineInactiveColor      = { bg     = colors.dark0 },
    BufferlineBackgroundColor    = { bg     = colors.dark0_hard },
    -- nvim-lightbulb
    LightBulbSign                = { fg     = colors.bright_yellow, bg = colors.dark1 },
    -- DAP(-UI)
    DapStoppedText               = { fg     = colors.bright_orange, bg = colors.dark1 },
    DapStoppedLine               = { bg     = colors.faded_orange },
    DapBreakpoint                = { fg     = colors.bright_red, bg = colors.dark1 },
    DapUIWatchesEmpty            = { link   = '@comment' },
    DapUIPlayPause               = { fg     = colors.bright_green },
    DapUIStepInto                = { fg     = colors.bright_blue },
    DapUIStepOver                = { fg     = colors.bright_blue },
    DapUIStepOut                 = { fg     = colors.bright_blue },
    DapUIStepBack                = { fg     = colors.bright_blue },
    DapUIRestart                 = { fg     = colors.bright_green },
    DapUIStop                    = { fg     = colors.bright_red },
    DapUILineNumber              = { link   = 'LineNr' },
    DapUIBreakpointsCurrentLine  = { link   = 'CursorLineNr' },
    DapUIType                    = { link   = '@type' },
    DapUISource                  = { link   = '@include' },
    DapUIDecoration              = { fg     = colors.gray },
    DapUIWatchesValue            = { fg     = colors.bright_green },
    DapUICurrentFrameName        = { link   = '@field' },
    DapUIScope                   = { link   = '@label' },
    DapUIModifiedValue           = { fg     = colors.bright_green, bold = true },
    DapUIThread                  = { link   = '@label' },
    DapUIStoppedThread           = { link   = '@comment' },
    DapUIBreakpointsPath         = { link   = '@label' },
    DapUIWatchesError            = { fg     = colors.neutral_red },
    -- DapUIFloatBorder             = { fg     = '#00F1F5' },
    -- DapUIBreakpointsInfo         = { fg     = '#A9FF68' },
    -- DapUIBreakpointsDisabledLine = { fg     = '#424242' },
    -- DapUIUnavailable             = { fg     = '#424242' },
  },
  dim_inactive         = false,
  transparent_mode     = false,
}
vim.cmd.colorscheme 'gruvbox'
